# Generated by Django 3.0.7 on 2020-06-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currentDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
