# Generated by Django 3.0.7 on 2020-06-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0002_post_currentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='CATEGORIES_CHOICES',
            field=models.CharField(choices=[('Sport', 'ספורט'), ('Health', 'בריאות'), ('Education', 'חינוך'), ('Shopping', 'קניות')], default='Education', max_length=10),
        ),
    ]
