# Generated by Django 3.0.7 on 2020-06-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0002_auto_20200630_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
