# Generated by Django 3.0.7 on 2020-06-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0003_post_categories_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='CATEGORIES_CHOICES',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('S', 'Sport'), ('E', 'Education'), ('H', 'Health')], default='S', max_length=1),
        ),
    ]
