# Generated by Django 3.0.7 on 2020-06-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0004_auto_20200701_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
