# Generated by Django 3.0.7 on 2020-06-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0007_auto_20200627_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Sport', 'Sport'), ('Education', 'Education'), ('Health', 'Health')], default='All', max_length=20),
        ),
    ]
