# Generated by Django 3.0.7 on 2020-06-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0009_auto_20200627_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
