# Generated by Django 3.0.7 on 2020-06-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0010_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
