# Generated by Django 3.0.7 on 2020-06-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0012_auto_20200628_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_counter',
            field=models.IntegerField(),
        ),
    ]
