# Generated by Django 3.0.7 on 2020-06-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0014_remove_post_views_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
