# Generated by Django 3.0.7 on 2020-06-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0015_post_views_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_counter',
            field=models.IntegerField(default=0),
        ),
    ]
