# Generated by Django 3.0.7 on 2020-06-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0016_auto_20200628_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_counter',
        ),
    ]
