# Generated by Django 3.0.7 on 2020-06-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSiteProj', '0018_post_views_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views_counter',
            new_name='views',
        ),
    ]
